app = "koola10-llm"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  OLLAMA_HOST = "0.0.0.0"

[http_service]
  internal_port = 11434
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "performance-8x"

[[mounts]]
  source = "ollama_data"
  destination = "/root/.ollama"
