app = "koola10-browser"
primary_region = "ams"

[http_service]
  internal_port = 8080

[mounts]
  source = "browser_data"
  destination = "/data"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpus = 2
  cpu_kind = "shared"
